kind: pipeline
name: default

steps:
- name: build
  image: smartprix/node:12
  commands:
  - yarn install
  - yarn lint
  - yarn build
  when:
    event:
    - tag
    - push

- name: npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
  when:
    event:
      tag

